name: pharmacy_app_updated
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  delightful_toast: ^1.1.0
  internet_connection_checker_plus: ^2.7.1
  uuid: ^4.5.1
  pretty_qr_code: ^3.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pharmacy_logo.png
